name: Update GitHub Profile README

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite (UTC)
  workflow_dispatch: # Permite execução manual

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Atualiza as estatísticas do README usando github-readme-stats
      - name: Update GitHub Stats
        uses: anmol098/waka-readme-stats@v1.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOCALE: en
          SHOW_PROFILE_VIEWS: true
          SHOW_TOP_LANGUAGES: true
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_SHORT_INFO: false
          SHOW_TOTAL_CODE_TIME: false
          COMMIT_MESSAGE: 'Atualiza estatísticas do README'

      # Faz commit das alterações no README
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Atualiza estatísticas do README" || echo "Nenhuma alteração para commit"
          git push
